### ISSUE TITLE
CIFilter outputImage: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by HyunjoonKo** [muukii/Brightroom#146]
<img width="1168" alt="ScreenShot 2021-09-08 PM 5 26 48" src="https://user-images.githubusercontent.com/3861180/132476327-6ea411f0-fc5f-4c96-a715-d798863b6f30.png">

The `CIFilter outputImage` in the `apply(to:sourceImage:)` function of the `FilterColorCube` class is returned as nil.

The LUT image used was:
![LUT_144_Apple Intense Cold](https://user-images.githubusercontent.com/3861180/132476531-2f6a780b-3d40-4216-80e3-056ba0e7cf97.jpeg)
_LUT_144_Apple Intense Cold.jpeg_

The dimension value is 144. What is wrong?

**Comment by muukii** [comment]
Brightroom does not support 144 size LUT, please use 64 dimension instead.

**Comment by HyunjoonKo** [comment]
I see. Thank you for answer 😁
