### ISSUE TITLE
How to disable "cube crop"

### ISSUE THREAD

**Issue by snake302** [muukii/Brightroom#15]
Hi there!

Few days I am trying to disable "cube cropping" to display image at it is (with same aspect ratio), but can't find correct lines at framework. 

Can you please explain me where is this function.

**Comment by muukii** [comment]
@snake302 
I'm sorry, Pixel currently supports square crop only.
So, PixelEditor is named as `Square'.
But I know Pixel should support oblong cropping.

**Comment by muukii** [comment]
@anonrig 
No, I don't have anyone currently. I know Pixel should have this feature.
But I don't have time to implement this. So I want someone's help.

**Comment by anonrig** [comment]
If you can guide me on this process, I would very much like to implement it.

**Comment by muukii** [comment]
And we need to decide detail of this feature and the scope of implementation.
I think I would like to separate steps to how to provide this feature.

**Comment by anonrig** [comment]
I’ll do an initial assesment and open a separate issue to discuss before implementing it. @muukii

**Comment by snake302** [comment]
Oops, sorry guys, my mistake

**Comment by janczakb** [comment]
Is there a solution to turn off square cropping?
