### ISSUE TITLE
Color profile is changing without applying any filter - SwiftUICropView

### ISSUE THREAD

**Issue by iamhtz** [muukii/Brightroom#167]
## Overview

I am using your library to crop different images and send them to a network call.
I noticed that when I give an image to your library it changes the color profile.
Are you processing any work on image? Are you planning to provide any API to avoid this automatic process?
Finally, thank you for your great work. 

## Details

I am using `SwiftUICropView`

Please check difference between this two following images

![original](https://user-images.githubusercontent.com/7542057/162223262-e150e9bc-a99c-4377-ae27-ce9fb63c4fcc.jpg)
**Original image**

![in-clipdrop-edition](https://user-images.githubusercontent.com/7542057/162223279-7a35e769-c56a-4b39-b42b-efc3591dcd9c.jpg)
**Processed by Brightroom image**

## Reproduce version

Brightroom 2.3.3

**Comment by muukii** [comment]
I see, it's changing DisplayP3 to sRGB.
How to render this image? Might solve this issue with specifying options.

**Comment by muukii** [comment]
OK, I fixed it.
From now, Renderer creates an image with original image's colorprofile
https://github.com/muukii/Brightroom/pull/168

**Comment by muukii** [comment]
If you need to get converted image, specify options in render()

**Comment by muukii** [comment]
https://github.com/muukii/Brightroom/releases/tag/2.6.0

**Comment by iamhtz** [comment]
Thank you for your great work @muukii ! 🚀

**Comment by muukii** [comment]
Sorry, I put a mistake.
this fixes https://github.com/muukii/Brightroom/pull/169
