### ISSUE TITLE
How can I edit the "Edit" Options?

### ISSUE THREAD

**Issue by harshjoshi096** [muukii/Brightroom#18]
Hi,
I want to remove some of the options which are provided in edit options, so can anyone let me know how can I remove unwanted options? 
For e.g, I need to remove the edit option 'Mask' and 'Adjust'.

Thanks

**Comment by muukii** [comment]
@harshjoshi096 
Thanks for your voice.
I understand that you want to do.
Actually, we don't provide such as to control features.
But, Maybe, You can do this with subclassing. 

1. Create a subclass of EditMenuControl and customize UI.
2. Set subclass you created to `Options.Classes.Control.editMenuControl`

But, EditMenuControl may not provide API to customize.
Let me know if you find some problems. or please submit a proposal as PR.

**Comment by ankur432020** [comment]
> Hi,
> I want to remove some of the options which are provided in edit options, so can anyone let me know how can I remove unwanted options?
> For e.g, I need to remove the edit option 'Mask' and 'Adjust'.
> 
> Thanks

options.classes.control.ignoredEditMenu = [.mask, .adjustment]
