### ISSUE TITLE
How to present controller with filters.

### ISSUE THREAD

**Issue by HussainTechGee** [muukii/Brightroom#19]
When i present controller like this

 let image2=UIImage.init(named: "22")
let controller = PixelEditViewController(image: image2!)
self.navigationController?.pushViewController(controller, animated: true)

it does not show filters list however editing image works perfectly.

it show output like 
![img_283691854914-1](https://user-images.githubusercontent.com/37771774/50556897-d7037580-0d00-11e9-8c62-a65843c0ea7b.jpeg)

**Comment by muukii** [comment]
@HussainTechGee 
Hi, 
Sorry about that. Pixel currently does not contain default filter(a.k.a preset).
However, the Demo app contains that. You can find how to install some filters.
And also it uses `ColorCubeStorage` to do that.
Please read [THIS DOCUMENT](https://github.com/muukii/Pixel#add-colorcubefilters).

**Comment by NiravBhuva** [comment]
@muukii Sir could you please explain how to install filters. Please.
