### ISSUE TITLE
Take 5-10 sec to load filters can we show it instantly?

### ISSUE THREAD

**Issue by tjsingh04** [muukii/Brightroom#24]

**Comment by Jasperav** [comment]
Pretty useless project if you ask me. The demo is **really** buggy, slow and unresponsive. How can this have so many stars?

**Comment by tjsingh04** [comment]
i don't think is it works well on device, but it take 4-5 secs in starting to load filters

**Comment by tjsingh04** [comment]
> Pretty useless project if you ask me. The demo is **really** buggy, slow and unresponsive. How can this have so many stars?

try it in real device rather than simulator
