### ISSUE TITLE
resize image in edit view

### ISSUE THREAD

**Issue by kuls14** [muukii/Brightroom#30]
I want to show full image in edit or filter view but at the moment I only get cropped image if image size is too large.
Any idea how to do this?

**Comment by Arideno** [comment]
@kuls14 Also interested.

**Comment by Arideno** [comment]
@kuls14 I found the answer. You should go to SquareEditingStack and comment all the code.

**Comment by kuls14** [comment]
@Arideno  I have tried your solution but it doesn't seem to work

**Comment by Rep2** [comment]
Same issue here. Image get's cropped first time that it's edited.

**Comment by UNLK8852** [comment]
@Rep2 I'm having the same issue. Have your figured out a fix?

**Comment by Rep2** [comment]
@UNLK8852 no, didn't find a solution

**Comment by janczakb** [comment]
does anyone know how to turn off square cropping?

**Comment by Jeplin** [comment]
If anyone still looking for a solution, this might help. Just look for a initialCrop function inside SquareEditingStack class. then just remove the custom square size. that's it ...

**Comment by Rep2** [comment]
@Jeplin thanks for the comment. A little bit of further investigation showed that the you can disable `SquareEditingStack` in `PixelEditViewController` using `usesSquareCropping: false` in init
