### ISSUE TITLE
Preview issue when load rectangular image

### ISSUE THREAD

**Issue by rayyagelski** [muukii/Brightroom#36]
Hello, when I open pixeleditor with rectangular image, it does not fit in ImagePreviewView. Is there any way that I can also use rectangualr image? It works well when I open with square image.

![image](https://user-images.githubusercontent.com/55295399/67156758-790a5200-f355-11e9-8fe9-ee59a70a9ca8.png)

**Comment by arturmichna** [comment]
@rayyagelski could you update to latest version 0.2.1. I think the issue has been fixed
