### ISSUE TITLE
How to apply filter on multiple images at once?

### ISSUE THREAD

**Issue by M-I-N** [muukii/Brightroom#41]
Is there any way to apply any filter to multiple images at once? 

I have a requirement where multiple images can be picked and passed to a scene which should be able to apply a filter by clicking any of the available filters. It's similar as how the multiple selection for [Instagram](https://www.instagram.com) works. I'm attaching a photo for easy understanding: 

![Screen Shot 2020-02-23 at 12 22 18 PM](https://user-images.githubusercontent.com/17010288/75104787-2ad4ca80-5637-11ea-8ca3-860a2c7854f8.png)

**Comment by likedan** [comment]
Same ask. Is there any way to do this?

**Comment by muukii** [comment]
Sorry, 
We do not have that feature.
