### ISSUE TITLE
Planning v2

### ISSUE THREAD

**Issue by muukii** [muukii/Brightroom#51]
A long time has passed from the first release.
And we've got many feature requests and some issues. Thank you for trying to use this library out.

Currently, I don't have enough time to maintain this lib but I'm thinking of how we could make it to be better than now.

Now I have followings:
- Recently, handling media software contains so many features and user interfaces, it seems the one application that can be released as a product. That's why I think it needs something good state-management (like [Verge](https://github.com/VergeGroup/Verge))
- The UI to modify image differs from each use-case in products. So it should be easy to switch with other types of UI. That's why I architected PixelEngine and PixelEditor.

**Comment by PingAK9** [comment]
Dear Muukii
This is my project with SwiftUI & your PixelEngine
https://github.com/PingAK9/photo-editor-luts-swiftui

Thanks for writing this very useful plugin! It works great.
