### ISSUE TITLE
High Memory Usage 

### ISSUE THREAD

**Issue by muukii** [muukii/Brightroom#6]
When we open PixelEditorViewController, memory usage is very high that can see with Instruments.
It seems that `ImageTool.resize` cause this.

<img width="1392" alt="2018-10-31 3 07 02" src="https://user-images.githubusercontent.com/1888355/47744230-2fe46c80-dcc4-11e8-97c0-b70ea880e9bf.png">

https://developer.apple.com/videos/play/wwdc2018/416/

**Comment by muukii** [comment]
@Banannzza 
Thank you.
I tried to do that. However, I think I would like to use a large image to zoom that.
And I know that will use so many memory. (but why is this so huge? around 300MB!)
But It may have a good way of drawing. Do you have any good way?

If there is no way, we have no choice. 
We will use a downsampled image from UIImagePickerController or PHAsset.

And, I did not know that `.imageURL`.
Definitely, we can resize that with ImageIO.

**Comment by Banannzza** [comment]
@muukii Yes, image decoding can cause memory problems. I don't know better way of drawing, but I will figure out if it exists.
