### ISSUE TITLE
Couldn't run project after install pods

### ISSUE THREAD

**Issue by FedupTech** [muukii/Brightroom#90]
Error message

Undefined symbols for architecture x86_64:
  "Brightroom.EditingStack.State.Loaded.currentEdit.setter : Brightroom.EditingStack.Edit", referenced from:
      key path setter for Brightroom.EditingStack.State.Loaded.currentEdit : Brightroom.EditingStack.Edit : Brightroom.EditingStack.State.Loaded in BlurryMaskingView.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

@muukii

**Comment by muukii** [comment]
@FedupTech 
okay, I can reproduce it.
I'll work on this issue tonight or tomorrow on this PR https://github.com/muukii/Brightroom/pull/91
Thanks for reporting.

**Comment by FedupTech** [comment]
> @FedupTech
> okay, I can reproduce it.
> I'll work on this issue tonight or tomorrow on this PR #91
> Thanks for reporting.

Thx
